# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json"}}
          - v1-dependencies-
      - run: npm install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json"}}
        run: npx cypress run

workflows:
  version: 2
  test-the-app:
    jobs:
      - test