version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run