version: 2.1
jobs:
  test:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run
      - run:
          name: Create merged-report Directory
          command: mkdir cypress/merged-report/      
      - run:
          name: Merge mochawesome jsons in one file
          when: always
          command: npx mochawesome-merge --reportDir mochawesome-report/ > cypress/merged-report/merged-report.json
      - run: ls
      - run:
          name: Generate mochawesome html report
          when: always
          command: npx marge cypress/merged-report/merged-report.json -o cypress/mochawesome-html-report
      - store_artifacts:
          name: Uploading mochawesome-merged-report.json
          path: cypress/merged-report
      - store_artifacts:
          name: Uploading mochawesome-html-report
          path: cypress/mochawesome-html-report     

      
workflows:
  gegenpressing:
    jobs:
      - test     